### PR TITLE
Change translation from Goslate to Google Translate API

### PR DESCRIPTION
**Pull request by RNabel**
**Reason**:
 - [Goslate](https://pypi.python.org/pypi/goslate) is abandoned, new translation mechanism needed

**New features**:
 - translation using [Google Translate API](https://developers.google.com/api-client-library/python/apis/translate/v2)
 - added parameter to specify Google Translate API key, (`-K API_KEY` or `--api-key API_KEY`)
 - Reformatted autosub file to comply with PEP8
 - *EDIT*: Source / destination language codes updated according to Google's docs and simplified the parameter from `--list-(src|dst)-languages` to `--list-languages`

**Fixes**:
 - #12

### CODE REVIEW

**Comment by agermanidis** [comment]
Hey, thanks a lot for this! Can you add the new library dependency to `setup.py`? After that I can merge this in.

**Comment by RNabel** [comment]
Hey, no problem!

I added the dependencies, and also updated the language codes according to Google's [Translate Documentation](https://cloud.google.com/translate/v2/using_rest#language-params) as the other codes broke the translation (i.e. `en-US`-style did not work and was replaced with `en`-type codes). 
Subsequently, the `--list-(src|dst)-languages` flags return the same codes, and I propose to simplify it to `--list-languages`.

Thoughts?

**Comment by agermanidis** [comment]
That looks good, but I wonder if we're losing transcription accuracy by not using the dialect-specific codes for the recognition (e.g. en-US). The Speech API is undocumented so it's hard to tell. What if you kept the source and destination codes and just passed `self.src.split('-')[0]` to the translator as src?

**Comment by agermanidis** [comment]
Did a few tests and it didn't seem like the dialect made any significant difference for the recognition accuracy, so I'll go ahead and merge this in, thanks again.

**Comment by RNabel** [comment]
Awesome! The README may also need updating. I'll have a look at that tomorrow.

**Pull request merged**
